# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'ConferenceApp' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for ConferenceApp

  # Required by RNFirebase
  pod 'Firebase/Core'

  # [OPTIONAL PODS] - comment out pods for firebase products you won't be using.
  pod 'Firebase/AdMob'
  pod 'Firebase/Auth'
  pod 'Firebase/Crash'
  pod 'Firebase/Database'
  pod 'Firebase/DynamicLinks'
  pod 'Firebase/Performance'
  pod 'Firebase/Firestore'
  pod 'Firebase/Messaging'
  pod 'Firebase/RemoteConfig'
  pod 'Firebase/Storage'

  pod 'Fabric', '~> 1.7.2'
  pod 'Crashlytics', '~> 3.9.3'
  pod 'react-native-spinkit', :path => '../node_modules/react-native-spinkit'
  pod 'react-native-background-timer', :path => '../node_modules/react-native-background-timer'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
